build:
  test-and-lint:
    image: node:8
    environment:
      - NPM_CONFIG_CACHE=/drone/.npm
      - NPM_CONFIG_LOGLEVEL=warn
    commands:
      - yarn
      - npm run preversion

cache:
  mount:
    - /drone/.npm
