resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: master
  type: git
  webhook_token: 0gd4XZNL4Y94zYDLql3C
  check_every: 30m
  source:
    uri: git@github.com:buildo/scriptoni
    branch: master
    private_key: ((private-key))

- name: pr
  type: pull-request
  webhook_token: 0gd4XZNL4Y94zYDLql3C
  check_every: 30m
  source:
    repository: buildo/scriptoni
    access_token: ((github-token))

jobs:
- name: test
  plan:
  - get: scriptoni
    resource: master
    trigger: true
  - task: test
    config: &test_config
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: 8
      inputs:
        - name: scriptoni
      caches:
        - path: scriptoni/node_modules
      run:
        path: sh
        args:
          - -c
          - |
            set -e
            cd scriptoni
            yarn install
            yarn test

- name: pr-test
  plan:
  - get: scriptoni
    resource: pr
    trigger: true
    version: every
  - put: pr
    params:
      path: scriptoni
      status: pending
      context: concourse
  - task: test
    config:
      <<: *test_config
    on_success:
      put: pr
      params:
        path: scriptoni
        status: success
        context: concourse
    on_failure:
      put: pr
      params:
        path: scriptoni
        status: failure
        context: concourse
